/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Denys Almaral (https://sketchfab.com/denysalmaral)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/clown-fish-low-poly-animated-af7ba2aa41d2413098a59b21cfda79c2
Title: Clown Fish Low Poly Animated
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

export const ClownFish = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/clown_fish.glb");
  const { actions } = useAnimations(animations, group);
  const viewport = useThree((state) => state.viewport);

  console.log(actions);
  useEffect(() => {
    const action = actions["swim_left"];

    if (action) {
      action.timeScale = 0.3; // アニメーション速度を半分にする
      action.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="de8a6d993d1648139d961f02b30f3fb3fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive
                    object={nodes._rootJoint}
                    position={[0, -viewport.height * 10, 0]}
                  />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.fishclown}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group
                    name="Object_6"
                    position={[0, 0.137, -2.214]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="fishClown"
                    position={[0, 0.137, -2.214]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/clown_fish.glb");
